version: "3.8"

x-app:
  &app-base
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  environment:
    REDIS_URL: redis://redis:6379
  command: "node index.js"
  tty: true
  stdin_open: true
  depends_on:
    - redis

services:
  redis:
    image: redis:7.0-alpine
    # ports:
    #   - 6379:6379
    # volumes:
    #   - redis:/data

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3

  app1:
    <<: *app-base
    container_name: server-1
    ports:
      - 3001:3000
  app2:
    <<: *app-base
    container_name: server-2
    ports:
      - 3002:3000
  app3:
    <<: *app-base
    container_name: server-3
    ports:
      - 3003:3000
