version: "3.8"

x-app:
  &app-base
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  command: "node index.js"
  tty: true
  stdin_open: true

services:
  nginx:
    image: nginx:latest
    ports:
      - 4444:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - app1
      - app2

  app:
    <<: *app-base
    environment:
      PORT: 8000
    ports:
      - 8000:8000
  app1:
    <<: *app-base
    environment:
      PORT: 8001
    ports:
      - 8001:8001
  app2:
    <<: *app-base
    environment:
      PORT: 8002
    ports:
      - 8002:8002

